version: "3.9"

services:
  db:
    image: postgres
    container_name: rpq
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PQ_USER}
      POSTGRES_PASSWORD: ${PQ_PASSWORD}
  web:
    container_name: rapp
    build: .
    image: rapp_in_docker:v1
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    user: ${CURRENT_UID}
    environment:
      HOME: /app

    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
